language: node_js
node_js:
  - 10
  - 8
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
